- name: Deploy agents
  hosts: all
  tasks:
    - name: Import agent role
      ansible.builtin.import_role:
        name: agent
      tags: deploy_agents

- name: Deploy db config
  hosts: all
  tasks:
    - name: Import mysql role
      ansible.builtin.import_role:
        name: mysql
      tags: deploy_db_config

- name: Deploy nginx config
  hosts: all
  tasks:
    - name: Import nginx role
      ansible.builtin.import_role:
        name: nginx
      tags: deploy_nginx_config